project_name: serve-static
builds:
    - main: main.go
      binary: serve-static
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64
archive:
    format: tar.gz
release:
    draft: false
